.set LOCALID_GRUNT_1, 1
.set LOCALID_GRUNT_2, 6
.set LOCALID_MIRO, 13

Route112_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route112_OnTransition
	.byte 0

Route112_OnTransition:
	clearflag FLAG_FORCE_MIRAGE_TOWER_VISIBLE
	setvar VAR_JAGGED_PASS_ASH_WEATHER, 0
	end

Route112_EventScript_MagmaGrunts::
	lockall
	delay 40
	applymovement LOCALID_GRUNT_1, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	delay 20
	msgbox Route112_Text_LeaderGoingToAwakenThing, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_GRUNT_1, Common_Movement_FaceOriginalDirection
	waitmovement 0
	delay 40
	applymovement LOCALID_GRUNT_2, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	delay 20
	msgbox Route112_Text_YeahWeNeedMeteorite, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_GRUNT_2, Common_Movement_FaceOriginalDirection
	waitmovement 0
	delay 40
	applymovement LOCALID_GRUNT_1, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	delay 20
	msgbox Route112_Text_OhThatsWhyCrewWentToFallarbor, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_GRUNT_1, Common_Movement_FaceOriginalDirection
	waitmovement 0
	delay 40
	applymovement LOCALID_GRUNT_2, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	delay 20
	msgbox Route112_Text_CantLetAnyonePassUntilTheyreBack, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_GRUNT_2, Common_Movement_FaceOriginalDirection
	waitmovement 0
	releaseall
	end

Route112_Text_MiroLookAround:
	face_up
	delay_16
	delay_8
	face_left
	delay_16
	delay_8
	face_down
	delay_16
	delay_8
	step_end

Route112_Text_MiroApproachLeft:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_down
	step_end

Route112_Text_MiroApproachRight:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_down
	step_end

Route112_EventScript_MtChimneyCableCarSign::
	msgbox Route112_Text_MtChimneyCableCarSign, MSGBOX_SIGN
	end

Route112_EventScript_MtChimneySign::
	msgbox Route112_Text_MtChimneySign, MSGBOX_SIGN
	end

Route112_EventScript_RouteSignLavaridge::
	msgbox Route112_Text_RouteSignLavaridge, MSGBOX_SIGN
	end

Route112_EventScript_Miro::
	lockall
	applymovement LOCALID_MIRO, Common_Movement_FacePlayer
	msgbox Route112_Text_MiroChill MSGBOX_AUTOCLOSE
	releaseall
	end

Route112_EventScript_MiroLost::
	addvar VAR_ROUTE112_MIRO, 1
	msgbox Route112_Text_MiroChill MSGBOX_AUTOCLOSE
	end

Route112_EventScript_MiroBattleLeft::
	playse SE_PIN
	applymovement LOCALID_MIRO, Common_Movement_ExclamationMark
	delay 16
	applymovement LOCALID_MIRO, Route112_Text_MiroApproachLeft
	waitmovement 0
	msgbox Route112_Text_MiroIntro MSGBOX_AUTOCLOSE
	applymovement LOCALID_MIRO, Route112_Text_MiroLookAround
	waitmovement 0
	goto_if_set FLAG_MIROWON, Route112_EventScript_MiroUpgradeTeam
	goto_if_unset FLAG_MIROWON, Route112_EventScript_MiroNoUpgradeTeam
	end

Route112_EventScript_MiroBattleRight::
	playse SE_PIN
	applymovement LOCALID_MIRO, Common_Movement_ExclamationMark
	delay 16
	applymovement LOCALID_MIRO, Route112_Text_MiroApproachRight
	waitmovement 0
	msgbox Route112_Text_MiroIntro MSGBOX_AUTOCLOSE
	applymovement LOCALID_MIRO, Route112_Text_MiroLookAround
	waitmovement 0
	goto_if_set FLAG_MIROWON, Route112_EventScript_MiroUpgradeTeam
	goto_if_unset FLAG_MIROWON, Route112_EventScript_MiroNoUpgradeTeam
	end

Route112_EventScript_MiroUpgradeTeam::
	trainerbattle_single TRAINER_MIRO4UPGRADE, Route112_Text_MiroIntro2, Route112_Text_MiroLost, Route112_EventScript_MiroLost
	end

Route112_EventScript_MiroNoUpgradeTeam::
	trainerbattle_single TRAINER_MIRO4UPGRADE, Route112_Text_MiroIntro2, Route112_Text_MiroLost, Route112_EventScript_MiroLost
	end

Route112_Text_MiroIntro:
	.string "Yooooo\p"
	.string "Bruv imagine these two dickheads\n"
	.string "blocking the way\p"
	.string "naaah now we gotta walk through\n"
	.string "a volcano??\p"
	.string "...$"

Route112_Text_MiroIntro2:
	.string "Yknow what Since you're here tho\n"
	.string "lemme cook you real quick.$"

Route112_Text_MiroLost:
	.string "I cant lie my hands were abit cold\n"
	.string "stiiiill$"

Route112_Text_MiroChill:
	.string "Listen an L is a W in disguise.\p"
	.string "You lose, you identify weakness,\n"
	.string "you adapt, you improve.\p"
	.string "Imma chill abit for these two to\n"
	.string "move.$"

Route112_EventScript_Hiker::
	msgbox Route112_Text_NotEasyToGetBackToLavaridge, MSGBOX_NPC
	end

Route112_EventScript_Larry::
	trainerbattle_single TRAINER_LARRY, Route112_Text_LarryIntro, Route112_Text_LarryDefeat
	msgbox Route112_Text_LarryPostBattle, MSGBOX_AUTOCLOSE
	end

Route112_EventScript_Carol::
	trainerbattle_single TRAINER_CAROL, Route112_Text_CarolIntro, Route112_Text_CarolDefeat
	msgbox Route112_Text_CarolPostBattle, MSGBOX_AUTOCLOSE
	end

Route112_EventScript_Bryant::
	trainerbattle_single TRAINER_BRYANT, Route112_Text_BryantIntro, Route112_Text_BryantDefeat
	msgbox Route112_Text_BryantPostBattle, MSGBOX_AUTOCLOSE
	end

Route112_EventScript_Shayla::
	trainerbattle_single TRAINER_SHAYLA, Route112_Text_ShaylaIntro, Route112_Text_ShaylaDefeat
	msgbox Route112_Text_ShaylaPostBattle, MSGBOX_AUTOCLOSE
	end

Route112_Text_LeaderGoingToAwakenThing:
	.string "Hey, man, is our leader really going\n"
	.string "to awaken that thing?$"

Route112_Text_YeahWeNeedMeteorite:
	.string "Sounds like it, yeah. But I heard\n"
	.string "we need a METEORITE to do it.$"

Route112_Text_OhThatsWhyCrewWentToFallarbor:
	.string "Oh, I get it now. That's why the rest\n"
	.string "of the crew went out to FALLARBOR.$"

Route112_Text_CantLetAnyonePassUntilTheyreBack:
	.string "You got it. And until they come back,\n"
	.string "we're not to let anyone pass, right.$"

Route112_Text_NotEasyToGetBackToLavaridge:
	.string "Eh, I'd like to get to MAUVILLE, but if\n"
	.string "I went down these ledges, it'd be no\l"
	.string "easy matter to get back to LAVARIDGE.$"

Route112_Text_MtChimneyCableCarSign:
	.string "MT. CHIMNEY CABLE CAR\n"
	.string "“A short walk {UP_ARROW} way!”$"

Route112_Text_MtChimneySign:
	.string "MT. CHIMNEY\p"
	.string "“For LAVARIDGE TOWN or the summit,\n"
	.string "please take the CABLE CAR.”$"

Route112_Text_RouteSignLavaridge:
	.string "ROUTE 112\n"
	.string "{LEFT_ARROW} LAVARIDGE TOWN$"

